spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        id: product-service
        uri: lb://product-service
        predicates: Path=/api/product
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}